import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Array of art pieces data with only the URLs populated
  const artPiecesData = [
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: true,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art1.png',
      imageUrlBack: '/artback1.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art2.png',
      imageUrlBack: '/artback2.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art3.png',
      imageUrlBack: '/artback3.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art4.png',
      imageUrlBack: '/artback4.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art5.png',
      imageUrlBack: '/artback5.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art6.png',
      imageUrlBack: '/artback6.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art7.png',
      imageUrlBack: '/artback7.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art8.png',
      imageUrlBack: '/artback8.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art9.png',
      imageUrlBack: '/artback9.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art10.png',
      imageUrlBack: '/artback10.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art11.png',
      imageUrlBack: '/artback11.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art12.png',
      imageUrlBack: '/artback12.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art13.png',
      imageUrlBack: '/artback13.png',
      clientId: null,
    },
    {
      title: '',
      description: '',
      medium: '',
      price: 0,
      isVertical: false,
      size: '',
      weight: '',
      inStock: true,
      imageUrlFront: '/art14.png',
      imageUrlBack: '/artback14.png',
      clientId: null,
    },
  ];

  for (const artPieceData of artPiecesData) {
    await prisma.artPiece.create({
      data: artPieceData,
    });
  }

  console.log(`Seeded ${artPiecesData.length} art pieces`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
