import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();
// weight in lbs
// size in inches
async function main() {
  const artPiecesData = [
    {
      title: '?',
      medium: 'oil',
      price: 150,
      isVertical: true,
      size: '6.5 x 10.5"',  
      weight: '0.8',
      inStock: true,
      imageUrlFront: '/art1.png',
      imageUrlBack: '/artback1.jpg', 
      clientId: null,
      height: '6.5',
      length: '10.5',
      shippingWidth: '3',
      shippingWeight: '3.8', 
    },
    {
      title: 'Charme vieilot',
      medium: 'oil',
      price: 350,
      isVertical: false,
      size: '18.5 x 22.5"',  
      weight: '4',
      inStock: true,
      imageUrlFront: '/art2.png',
      imageUrlBack: '/artback2.jpg', 
      clientId: null,
      height: '18.5',
      length: '22.5',
      shippingWidth: '3',
      shippingWeight: '7',
    },
    {
      title: 'Féérie hivernale',
      medium: 'oil',
      price: 275,
      isVertical: false,
      size: '14 x 18"', 
      weight: '3.6',
      inStock: true,
      imageUrlFront: '/art3.png',
      imageUrlBack: '/artback3.jpg',  
      clientId: null,
      height: '14',
      length: '18',
      shippingWidth: '3',
      shippingWeight: '6.6',
    },
    {
      title: 'Féérie hivernale',
      medium: 'oil',
      price: 200,
      isVertical: false,
      size: '12 x 17.5"', 
      weight: '2.2',
      inStock: true,
      imageUrlFront: '/art4.png',
      imageUrlBack: '/artback4.jpg',
      clientId: null,
      height: '12',
      length: '17.5',
      shippingWidth: '3',
      shippingWeight: '5.2',
    },
    {
      title: 'Les rayons du soleil couchent',
      medium: 'oil',
      price: 150,
      isVertical: false,
      size: '12 x 14"', 
      weight: '1.8',
      inStock: true,
      imageUrlFront: '/art5.png',
      imageUrlBack: '/artback5.jpg',
      clientId: null,
      height: '12',
      length: '14',
      shippingWidth: '3',
      shippingWeight: '4.8',
    },
    {
      title: 'Détente ',
      medium: 'oil',
      price: 300,
      isVertical: false,
      size: '15 x 20"', 
      weight: '3',
      inStock: false,
      imageUrlFront: '/art6.png',
      imageUrlBack: '/artback6.jpg',
      clientId: null,
      height: '15',
      length: '20',
      shippingWidth: '3',
      shippingWeight: '6',
    },
    {
      title: 'Refuge',
      medium: 'oil',
      price: 500,
      isVertical: false,
      size: '20 x 25"', 
      weight: '4',
      inStock: false,
      imageUrlFront: '/art7.png',
      imageUrlBack: '/artback7.jpg',  
      clientId: null,
      height: '20',
      length: '25',
      shippingWidth: '3',
      shippingWeight: '7',
    },
    {
      title: "Un regard vers l'avenir ",
      medium: 'oil',
      price: 300,
      isVertical: false,
      size: '19 x 25"', 
      weight: '4',
      inStock: true,
      imageUrlFront: '/art8.png',
      imageUrlBack: '/artback8.jpg',  
      clientId: null,
      height: '19',
      length: '25',
      shippingWidth: '3',
      shippingWeight: '7',
    },
    {
      title: 'Luminosité',
      medium: 'oil',
      price: 400,
      isVertical: false,
      size: '15 x 25"',  
      weight: '3.4',
      inStock: true,
      imageUrlFront: '/art9.png',
      imageUrlBack: '/artback9.jpg', 
      clientId: null,
      height: '15',
      length: '25',
      shippingWidth: '3',
      shippingWeight: '6.4',
    },
    {
      title: 'Éloge a la nature ',
      medium: 'oil',
      price: 425,
      isVertical: false,
      size: '22.5 x 26.5"', 
      weight: '5.2',
      inStock: true,
      imageUrlFront: '/art10.png',
      imageUrlBack: '/artback10.jpg', 
      clientId: null,
      height: '22.5',
      length: '26.5',
      shippingWidth: '3',
      shippingWeight: '8.2',
    },
    {
      title: "L'écho d'automne qui résonne",
      medium: 'oil',
      price: 450,
      isVertical: false,
      size: '25 x 29"',  
      weight: '5.6',
      inStock: true,
      imageUrlFront: '/art11.png',
      imageUrlBack: '/artback11.jpg',  
      clientId: null,
      height: '25',
      length: '29',
      shippingWidth: '3',
      shippingWeight: '8.6',
    },
    {
      title: 'Les merveilles de la nature',
      medium: 'oil',
      price: 450,
      isVertical: false,
      size: '25 x 33"', 
      weight: '7.8',
      inStock: true,
      imageUrlFront: '/art12.png',
      imageUrlBack: '/artback12.jpg',  
      clientId: null,
      height: '25',
      length: '33',
      shippingWidth: '3',
      shippingWeight: '10.8',
    },
    {
      title: 'Ressource Chalevoix',
      medium: 'oil',
      price: 450,
      isVertical: false,
      size: '22 x 28"',
      weight: '4.4',
      inStock: true,
      imageUrlFront: '/art13.png',
      imageUrlBack: '/artback13.jpg',  
      clientId: null,
      height: '22',
      length: '28',
      shippingWidth: '3',
      shippingWeight: '7.4', 
    },
    {
      title: 'Un souvenir de jeunesse',
      medium: 'oil',
      price: 350,
      isVertical: true,
      size: '19 x 23"',  
      weight: '4.2',
      inStock: true,
      imageUrlFront: '/art14.png',
      imageUrlBack: '/artback14.jpg',  
      clientId: null,
      height: '19',
      length: '23',
      shippingWidth: '3',
      shippingWeight: '7.2', 
    },
  ];
  

  for (const artPieceData of artPiecesData) {
    await prisma.artPiece.create({
      data: artPieceData,
    });
  }

  console.log(`Seeded ${artPiecesData.length} art pieces`);
}

main()
.then(async () => {
  await prisma.$disconnect()
})
  .catch((e) => {
    console.error(e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
